name: talatah
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^3.5.7
  flutter_form_builder: ^7.0.0
  font_awesome_flutter: ^9.2.0
  form_builder_validators: ^7.2.0
  get: ^4.6.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/jpg/
